In [50]:
import pandas as pd

In [51]:
csv_file = r'C:\Users\jbubeck2\Downloads\langchain_csv-main\Data\Kununu_reviews_audi_bmw_mercedes.csv'
df = pd.read_csv(csv_file)

C:\Users\jbubeck2\AppData\Local\Temp\ipykernel_14600\1809276135.py:2: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file)

In [52]:
df.head()

,title,score,createdAt,updatedAt,recommended,position,department,job_state,company.id,company.name,...,score_employmentSecurity,text_accessibility,text_diversity,text_security,text_employmentSecurity,text_positive,text_negative,text_suggestion,company,ID
0,Guter Arbeitgeber mit fairem Lohn,3.8,2022-02-17T00:00:00+00:00,2022-02-17T00:00:00+00:00,True,employee,sales,current,109455,AUDI AG Ingolstadt,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Audi,1
1,Vogelwild,2.9,2022-02-09T00:00:00+00:00,2022-02-09T00:00:00+00:00,False,manager,research,current,1502775,Audi,...,NaN,NaN,NaN,NaN,NaN,"Gute Ausstattung, soziale Sicherheit (bin gesp...","keine Konsequenz, Projekte hochrot, werden irg...",Gute Industrieschauspieler sind keine guten Ma...,Audi,2
2,Guter Arbeitgeber,4.3,2022-02-08T00:00:00+00:00,2022-02-08T00:00:00+00:00,True,employee,sales,current,109455,AUDI AG Ingolstadt,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Audi,3
3,Leider nicht studiert,3.1,2022-01-31T00:00:00+00:00,2022-01-31T00:00:00+00:00,False,employee,operations,current,1502775,Audi,...,NaN,NaN,NaN,NaN,NaN,Das Gehalt lässt einen über vieles hinwegsehen.,"Was ""integer"" bedeutet sollte eventuell nochma...",Die Firma sollte mit ihren eigenen Mitarbeiter...,Audi,4
4,Top Arbeitgeber,4.7,2022-01-28T00:00:00+00:00,2022-01-28T00:00:00+00:00,True,employee,research,current,348351,Audi AG Neckarsulm,...,NaN,NaN,NaN,NaN,NaN,Die Vielfalt und der offene Umgang.,NaN,NaN,Audi,5

In [53]:
selected_columns = ["title", "score", "createdAt", "recommended", "position", "department", "job_state", "company.name", "company.location.city", "text_positive", "text_negative", "text_suggestion", "company", "ID"]

In [54]:
selected_df_100 = df[selected_columns].sample(n=100)

In [55]:
selected_df_1000 = df[selected_columns].sample(n=1000)

In [56]:
selected_df_2000 = df[selected_columns].sample(n=2000)

In [57]:
selected_df_5000 = df[selected_columns].sample(n=5000)

In [58]:
selected_df_100.head()

,title,score,createdAt,recommended,position,department,job_state,company.name,company.location.city,text_positive,text_negative,text_suggestion,company,ID
195,"Ein super Job,eine super Firma.",4.3,2019-07-08T00:00:00+00:00,True,employee,operations,current,Audi,Ingolstadt,"Gute Bezahlung,angenehmes Arbeitsklima.","Diesel Skandal,schlecht für die Umwelt.","Mehr auf die Umwelt achten,kein Betrug mehr.",Audi,196
2699,Innovativ und trotzdem konservativ.,3.8,2016-06-28T00:00:00+00:00,True,employee,NaN,current,BMW Financial Services Holding GmbH,München,"Sozialleistungen, Bezüge, Entwicklungsmöglichk...","Zuviele Hierarchien, etwas angestaubte Prozesse",NaN,BMW,2700
2293,Gut: 3.85 von 5 Sternen,3.8,2018-06-27T00:00:00+00:00,True,employee,operations,current,BMW,München,"ein super, interessante arbeitgeber, der keine...",die arbeitsforderung sind hoch gesteckt,diedynamische anpassung an projekte musskurzfr...,BMW,2294
471,"AUDI AG, 4.2 von 5",4.2,2017-07-10T00:00:00+00:00,True,employee,NaN,current,Audi AG,Ingolstadt,"Sicherer Arbeitsplatz, geregeltes Einkommen","schlechte Aufstiegsmöglichkeiten, durch Abgass...",NaN,Audi,472
1213,Referentin,4.7,2015-11-09T00:00:00+00:00,True,employee,controlling,current,Audi,Ingolstadt,NaN,NaN,NaN,Audi,1214

In [59]:
selected_df_100.to_csv('Data/HR-Analytics_kununu_reviews_100.csv', index=False)
selected_df_1000.to_csv('Data/HR-Analytics_kununu_reviews_1000.csv', index=False)
selected_df_2000.to_csv('Data/HR-Analytics_kununu_reviews_2000.csv', index=False)
selected_df_5000.to_csv('Data/HR-Analytics_kununu_reviews_5000.csv', index=False)